### ISSUE TITLE
利用【【】】和{{}}引用的时候前面的标签消失了

### ISSUE THREAD

**Issue by bengirl2021** [mindstudy/siyuan-themes-concise-dark#1]
![image](https://user-images.githubusercontent.com/101393495/169505703-738f2a7f-1527-4326-9b29-583db28de0a5.png)

**Comment by bengirl2021** [comment]
那些Aa，H1，H2那些标签，没有那些引用的时候不方便，不知道自己引用了标题还是只是引用了一个小段落

**Comment by mindstudy** [comment]
<img width="582" alt="Screen Shot 2022-05-20 at 8 04 27 PM" src="https://user-images.githubusercontent.com/23169045/169524513-0167caee-3514-4fbf-ab99-c391cdf542f9.png">

Concise Dark 目前的版本为2.0.6，显示是正常的，效果如上。

可去集市更新一下主题，适配思源笔记版本为 2.0.11

**Comment by bengirl2021** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，作业已收到，谢谢

**Comment by bengirl2021** [comment]
> 最好

可以可以，微软商店的更新太慢了，才2.09，怪不得，谢谢

**Comment by bengirl2021** [comment]
> <img width="582" alt="Screen Shot 2022-05-20 at 8 04 27 PM" src="https://user-images.githubusercontent.com/23169045/169524513-0167caee-3514-4fbf-ab99-c391cdf542f9.png">
> 
> Concise Dark 目前的版本为2.0.6，适配思源笔记版本为 2.0.11，显示是正常的，效果如上。
> 
> 可去集市更新一下主题，（思源笔记最好也更新到最新版2.0.11，不然可能有些地方显示效果不佳）
> 
> 
> 

微软商店的思源更新太慢了，谢谢
